# ---------------------------------------------------------------------------
# Copy this file to a location OUTSIDE the repository, fill it in, and point
# WGR_CONFIG at it. It holds private keys and passwords, so it must never be
# committed.
#
#   cp config.example.tfvars ~/somewhere-private/wireguard-router.tfvars
#   export WGR_CONFIG=~/somewhere-private/wireguard-router.tfvars
#
# Every value here is cloud-agnostic: the same file drives the linode, aws,
# gcp and azure stacks unchanged. Cloud-specific settings go in a separate
# <platform>.tfvars file alongside this one - see "Provider selection" below.
# ---------------------------------------------------------------------------

node_name = "wg-router"
timezone  = "Europe/London"

# --- SSH access -------------------------------------------------------------

admin_username = "wgadmin"

# The public half of the key(s) you will SSH with. Password login is disabled.
# Add one entry per device or person that needs access.
ssh_public_keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... you@yourmachine",
  # "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... you@laptop",
]

# Non-default port; sshd will not be reachable on 22.
ssh_port = 58022

# Narrow this to your own network if you have a static address.
allowed_ssh_cidrs = ["0.0.0.0/0"]

# --- WireGuard --------------------------------------------------------------

# Non-default UDP port. Clients must use this in their Endpoint.
wireguard_port = 47654

wireguard_address = "10.66.66.1/24"

# Optional: only needed if you want "auto" client routes (below) to cover a
# wider range than wireguard_address's own /prefix - e.g. reserving a /16 so
# future peers can use a different /24 within it without changing this file.
# Leave unset to just derive it from wireguard_address, which is almost
# always what you want.
# wireguard_subnet = "10.66.0.0/16"

# Route peers' general internet traffic out through the server.
wireguard_nat = true

# Optional network-wide default DNS handed to peers that don't set their own
# override (see ./scripts/wg-peer.sh add --dns). Can be an address inside a
# peer's routed LAN, e.g. a router or Pi-hole reachable through the tunnel.
# wireguard_dns = "10.2.73.1"

# Optional network-wide default client-side AllowedIPs. "auto" computes the
# tunnel network plus every other peer's own address and LAN subnet, so a
# mesh of site-to-site peers can reach each other without routing general
# internet traffic through the server too. A literal CIDR list is used as-is.
# Empty (the default) means full tunnel: every peer routes everything through
# the server. Either can still be overridden per-invocation with
# WGR_CLIENT_ROUTES, e.g. to temporarily go full-tunnel from one device.
# wireguard_client_routes = "auto"

# NOTE: wireguard_private_key and wireguard_peers are deliberately absent here.
# They are generated by scripts/wg-peer.sh into the key store and supplied to
# OpenTofu automatically:
#
#   ./scripts/wg-peer.sh add laptop 10.66.66.2
#
# Do not set them in this file. ./wgr passes the generated file after this one,
# so anything you put here would be silently overridden (it will warn you).

# --- Dynu dynamic DNS -------------------------------------------------------

dynu_hostname = "yourname.freeddns.org"

# Authenticate with an API key, from Control Panel -> API Credentials.
# Preferred over username/password: it can be revoked on its own, and it does
# not grant control-panel access if this server is ever compromised.
dynu_api_key = "your-dynu-api-key"

# Alternative: the legacy IP-update protocol, which does not accept an API key.
# Set these *instead of* dynu_api_key, never both.
# dynu_username = "your-dynu-username"
# dynu_password = "your-dynu-password"

dynu_update_interval = "5min"

# --- Provider selection -----------------------------------------------------
#
# Cloud-specific settings (region/zone, instance size, image, etc.) live in
# their own file, not here - one per platform, named after it and placed in
# the same directory as this file:
#
#   cp linode.example.tfvars       "$(dirname "$WGR_CONFIG")/linode.tfvars"
#   cp aws.example.tfvars          "$(dirname "$WGR_CONFIG")/aws.tfvars"
#   cp gcp.example.tfvars          "$(dirname "$WGR_CONFIG")/gcp.tfvars"
#   cp azure.example.tfvars        "$(dirname "$WGR_CONFIG")/azure.tfvars"
#   cp digitalocean.example.tfvars "$(dirname "$WGR_CONFIG")/digitalocean.tfvars"
#
# ./wgr loads the one matching whichever platform you run it with, e.g.
# `./wgr gcp apply` loads gcp.tfvars. You only need to create the file(s) for
# the platform(s) you actually use.
#
# Credentials are best left out of every tfvars file and exported in your
# shell instead, as shown in each platform's example file.
