# ---------------------------------------------------------------------------
# Copy this file to a location OUTSIDE the repository, fill it in, and point
# WGR_CONFIG at it. It holds private keys and passwords, so it must never be
# committed.
#
#   cp config.example.tfvars ~/somewhere-private/wireguard-router.tfvars
#   export WGR_CONFIG=~/somewhere-private/wireguard-router.tfvars
#
# Every value here is cloud-agnostic: the same file drives the linode, aws,
# gcp and azure stacks unchanged.
# ---------------------------------------------------------------------------

node_name = "wg-router"
timezone  = "Europe/London"

# --- SSH access -------------------------------------------------------------

admin_username = "wgadmin"

# The public half of the key you will SSH with. Password login is disabled.
ssh_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... you@yourmachine"

# Non-default port; sshd will not be reachable on 22.
ssh_port = 58022

# Narrow this to your own network if you have a static address.
allowed_ssh_cidrs = ["0.0.0.0/0"]

# --- WireGuard --------------------------------------------------------------

# Non-default UDP port. Clients must use this in their Endpoint.
wireguard_port = 47654

wireguard_address = "10.66.66.1/24"

# Route peers' general internet traffic out through the server.
wireguard_nat = true

# Optional network-wide default DNS handed to peers that don't set their own
# override (see ./scripts/wg-peer.sh add --dns). Can be an address inside a
# peer's routed LAN, e.g. a router or Pi-hole reachable through the tunnel.
# wireguard_dns = "10.2.73.1"

# NOTE: wireguard_private_key and wireguard_peers are deliberately absent here.
# They are generated by scripts/wg-peer.sh into the key store and supplied to
# OpenTofu automatically:
#
#   ./scripts/wg-peer.sh add laptop 10.66.66.2
#
# Do not set them in this file. ./wgr passes the generated file after this one,
# so anything you put here would be silently overridden (it will warn you).

# --- Dynu dynamic DNS -------------------------------------------------------

dynu_hostname = "yourname.freeddns.org"

# Authenticate with an API key, from Control Panel -> API Credentials.
# Preferred over username/password: it can be revoked on its own, and it does
# not grant control-panel access if this server is ever compromised.
dynu_api_key = "your-dynu-api-key"

# Alternative: the legacy IP-update protocol, which does not accept an API key.
# Set these *instead of* dynu_api_key, never both.
# dynu_username = "your-dynu-username"
# dynu_password = "your-dynu-password"

dynu_update_interval = "5min"

# --- Provider selection -----------------------------------------------------
#
# Uncomment exactly ONE of the four blocks below, and leave the rest commented.
#
# Two reasons this matters:
#   * Each stack only declares its own platform variables, and OpenTofu treats
#     a variable it does not declare as an error. A stray gcp_project while
#     running the linode stack will stop the plan.
#   * instance_type is used by both linode and aws, and image by both linode
#     and gcp. With two blocks live, OpenTofu refuses to load the file at all
#     ("Attribute redefined") rather than picking one silently - so this fails
#     loudly, but it is still simplest to keep only one block uncommented.
#
# Credentials are best left out of this file entirely and exported in your
# shell instead, as shown per provider.

# --- Linode -----------------------------------------------------------------
# Credentials: export LINODE_TOKEN=...
# Run with:    ./wgr linode apply

region        = "eu-west"     # London. us-east = Newark, ap-south = Singapore
instance_type = "g6-nanode-1" # cheapest plan, 1 GB
image         = "linode/ubuntu24.04"
# linode_token  = "..."   # only if you would rather not use LINODE_TOKEN

# --- AWS --------------------------------------------------------------------
# Credentials: export AWS_PROFILE=... (or the standard AWS_* variables)
# Run with:    ./wgr aws apply
#
# architecture must match instance_type: arm64 for t4g.*, x86_64 for t3.*.

# aws_region    = "eu-west-2" # London
# instance_type = "t4g.nano"  # cheapest current generation, arm64
# architecture  = "arm64"
# vpc_id        = ""          # empty = the account's default VPC
# subnet_id     = ""          # empty = pick a subnet automatically

# --- GCP --------------------------------------------------------------------
# Credentials: gcloud auth application-default login
# Run with:    ./wgr gcp apply
#
# gcp_project is required - there is no sensible default for it.
# e2-micro is free-tier eligible only in us-west1, us-central1 and us-east1.

# gcp_project  = "my-project-id"
# gcp_zone     = "us-central1-a"
# machine_type = "e2-micro"
# image        = "ubuntu-os-cloud/ubuntu-2404-lts-amd64"
# network      = "default"

# --- Azure ------------------------------------------------------------------
# Credentials: az login (or the standard ARM_* service-principal variables)
# Run with:    ./wgr azure apply

# azure_location        = "uksouth"
# vm_size               = "Standard_B1ls" # cheapest Linux size, 0.5 GiB
# azure_subscription_id = "..."           # or export ARM_SUBSCRIPTION_ID
