# ---------------------------------------------------------------------------
# Copy this file to a location OUTSIDE the repository, fill it in, and point
# WGR_CONFIG at it. It holds private keys and passwords, so it must never be
# committed.
#
#   cp config.example.tfvars ~/somewhere-private/wireguard-router.tfvars
#   export WGR_CONFIG=~/somewhere-private/wireguard-router.tfvars
#
# Every value here is cloud-agnostic: the same file drives the linode, aws,
# gcp and azure stacks unchanged.
# ---------------------------------------------------------------------------

node_name = "wg-router"
timezone  = "Europe/London"

# --- SSH access -------------------------------------------------------------

admin_username = "wgadmin"

# The public half of the key you will SSH with. Password login is disabled.
ssh_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... you@yourmachine"

# Non-default port; sshd will not be reachable on 22.
ssh_port = 58022

# Narrow this to your own network if you have a static address.
allowed_ssh_cidrs = ["0.0.0.0/0"]

# --- WireGuard --------------------------------------------------------------

# Non-default UDP port. Clients must use this in their Endpoint.
wireguard_port = 47654

wireguard_address = "10.66.66.1/24"

# Route peers' general internet traffic out through the server.
wireguard_nat = true

# NOTE: wireguard_private_key and wireguard_peers are deliberately absent here.
# They are generated by scripts/wg-peer.sh into the key store and supplied to
# OpenTofu automatically:
#
#   ./scripts/wg-peer.sh add laptop 10.66.66.2
#
# Do not set them in this file. ./wgr passes the generated file after this one,
# so anything you put here would be silently overridden (it will warn you).

# --- Dynu dynamic DNS -------------------------------------------------------

dynu_hostname        = "yourname.freeddns.org"
dynu_username        = "your-dynu-username"
dynu_password        = "your-dynu-password"
dynu_update_interval = "5min"

# --- Provider selection -----------------------------------------------------
# Only the block matching the stack you run is used; unknown variables in a
# var file are an error, so keep just the ones you need or leave all of them
# (each stack declares its own, so remove blocks for stacks you never run).

# Linode
region        = "eu-west"
instance_type = "g6-nanode-1"
linode_token  = "" # prefer: export LINODE_TOKEN=...
